[package]
name        = "bloom"
version     = "0.0.1"
authors     = ["Will Johnston"]

description = "Space efficient probabilistic hash set"
repository  = "https://github.com/wbjohnston/bloom-filter"
license     = "MIT"
readme      = "README.md"

[dependencies]
bit-vec = "0.4.4"
